GET http://localhost:7071/players

###
POST http://localhost:8081/players/teams
Content-Type: application/json

{
  "teamName": "Example Team",
  "coachName": "Example Coach",
  "league": "Example League",
  "sponsorsName": "Example Sponsor",
  "foundingYear": 2000
}







